# .readthedocs.yaml
# Read the Docs configuration file for zlmdb
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Include .ai submodule for AI/audit related docs to be included in built docs (via symlinks)
# Include .cicd submodule for shared Sphinx extensions (sphinx_auto_section_anchors)
submodules:
  include:
    - .ai
    - .cicd
  recursive: false

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  # Install system packages for spell checking and LMDB/CFFI build
  apt_packages:
    - libenchant-2-2
    - build-essential
    - libffi-dev
    - libbz2-dev
    - libsnappy-dev

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    # Install the package with docs dependencies
    - method: pip
      path: .
      extra_requirements:
        - docs
