# automatically generated by the FlatBuffers compiler, do not modify

# namespace: survey

# /// Gender (simplified;).
class Gender(object):
# /// Unset or unknown gender.
    UNSET = 0
# /// Gender is male.
    MALE = 1
# /// Gender is female.
    FEMALE = 2

