# automatically generated by the FlatBuffers compiler, do not modify

# namespace: survey

import flatbuffers

# /// Ice cream surveys.
class IceCreamOfTheDaySurvey(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIceCreamOfTheDaySurvey(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IceCreamOfTheDaySurvey()
        x.Init(buf, n + offset)
        return x

    # IceCreamOfTheDaySurvey
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

# /// Unix epoch (UTC) when survey expires.
    # IceCreamOfTheDaySurvey
    def Expires(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # IceCreamOfTheDaySurvey
    def Moo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # IceCreamOfTheDaySurvey
    def Test1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .AccelSample import AccelSample
            obj = AccelSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IceCreamOfTheDaySurvey
    def Test2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TimeRange import TimeRange
            obj = TimeRange()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def IceCreamOfTheDaySurveyStart(builder): builder.StartObject(4)
def IceCreamOfTheDaySurveyAddExpires(builder, expires): builder.PrependUint64Slot(0, expires, 0)
def IceCreamOfTheDaySurveyAddMoo(builder, moo): builder.PrependUint8Slot(1, moo, 0)
def IceCreamOfTheDaySurveyAddTest1(builder, test1): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(test1), 0)
def IceCreamOfTheDaySurveyAddTest2(builder, test2): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(test2), 0)
def IceCreamOfTheDaySurveyEnd(builder): return builder.EndObject()
