# automatically generated by the FlatBuffers compiler, do not modify

# namespace: accelstorage

import flatbuffers

# /// A batch of sample series.
class AccelBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAccelBatch(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AccelBatch()
        x.Init(buf, n + offset)
        return x

    # AccelBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AccelBatch
    def Series(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .AccelSeries import AccelSeries
            obj = AccelSeries()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AccelBatch
    def SeriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AccelBatch
    def Test(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def AccelBatchStart(builder): builder.StartObject(2)
def AccelBatchAddSeries(builder, series): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(series), 0)
def AccelBatchStartSeriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AccelBatchAddTest(builder, test): builder.PrependInt32Slot(1, test, 0)
def AccelBatchEnd(builder): return builder.EndObject()
