# automatically generated by the FlatBuffers compiler, do not modify

# namespace: accelstorage

import flatbuffers

# /// No sample series matching the criteria could be found.
class NoSuchSeries(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNoSuchSeries(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NoSuchSeries()
        x.Init(buf, n + offset)
        return x

    # NoSuchSeries
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def NoSuchSeriesStart(builder): builder.StartObject(0)
def NoSuchSeriesEnd(builder): return builder.EndObject()
